- name: Setup VPS
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - python3-passlib
          - ufw
          - zsh
          - fail2ban
          - vim
        state: present
        update_cache: yes

      # docker playbook
    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is enabled and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    # user playbook
    - name: Create a new user
      user:
        name: "{{ lookup('env', 'NEW_USER_NAME') }}"
        password: "{{ lookup('env', 'NEW_USER_PASSWORD') | password_hash('sha512') }}"
        shell: /bin/zsh
        state: present
        create_home: yes
    
    - name: Add user to sudo group
      user:
        name: "{{ lookup('env', 'NEW_USER_NAME') }}"
        groups: sudo  
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ lookup('env', 'NEW_USER_NAME') }}"
        line: "{{ lookup('env', 'NEW_USER_NAME') }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'

    # oh my zsh playbook

    - name: Download Oh My Zsh installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: '0755'

    - name: Install Oh My Zsh for sysadmin
      command: sh /tmp/install_ohmyzsh.sh --unattended
      args:
        creates: "/home/{{ lookup('env', 'NEW_USER_NAME') }} /.oh-my-zsh"
      become: true
      become_user: "{{ lookup('env', 'NEW_USER_NAME') }}"
    
    # ssh playbook
    - name: Update SSH port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: "Port {{ lookup('env', 'NEW_SSH_PORT')}}"
        validate: '/usr/sbin/sshd -t -f %s'
      notify: 
        - restart ssh
        - restart sshd

    - name: Add SSH key for sysadmin
      ansible.builtin.authorized_key:
        user: "{{ lookup('env', 'NEW_USER_NAME') }}"
        key: "{{ lookup('file', 'authorized_keys') }}"
        state: present

    - name: Restrict login by root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin '
        line: "PermitRootLogin no"
        validate: '/usr/sbin/sshd -t -f %s'  # Checks syntax before saving
      notify: 
        - restart ssh 
        - restart sshd

    - name: Restrict login via password
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication '
        line: "PasswordAuthentication no"
        validate: '/usr/sbin/sshd -t -f %s'  # Checks syntax before saving
      notify:
        - restart ssh
        - restart sshd

    - name: Set login via pub key
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication '
        line: "PubkeyAuthentication yes"
        validate: '/usr/sbin/sshd -t -f %s'  # Checks syntax before saving
      notify:
        - restart ssh
        - restart sshd
      
  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted
    
    - name: Start and enable the fail2ban service
      ansible.builtin.systemd_service:
        name: fail2ban
        state: started
        enabled: true
    
    - name: Start and enable the UFW service
      ansible.builtin.systemd_service:
        name: ufw
        state: started
        enabled: true
